class LoginErrorCode {
  static PHONE_REQUIRED = 'PHONE_REQUIRED';
  static PHONE_INVALID = 'PHONE_INVALID';
  static PASSWORD_REQUIRED = 'PASSWORD_REQUIRED';
  static ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND';
  static PASSWORD_INCORRECT = 'PASSWORD_INCORRECT';
  static SESSION_WRITE_FAILED = 'SESSION_WRITE_FAILED';
  static SESSION_ERROR = 'SESSION_ERROR';
}
